[package]
name = "habitctl"
version = "0.3.1"
authors = ["Sebastian Morr <sebastian@morr.cc>", "Daryl Manning <daryl@wakatara.com>"]
description = "Minimalist command line tool you can use to track and examine your habits."

[dependencies]
chrono = "0.4.10"
rprompt = "1.0.3"
clap = "2.32.0"
open = "1.2.2"
dirs = "1.0.3"
libmath = "0.1.4"
